### ISSUE TITLE
types in moduleIncludes block

### ISSUE THREAD

**Issue by ericprud** [kylejlin/tyson#7]
[#6] includes the `%{...%}`  code block into the generated TS file. This is fine for constants but problematic for code that needs typing because jison's output isn't typescript-friendly. I'm tooling away on this now.

**Comment by ericprud** [comment]
[ts-jison](https://www.npmjs.com/package/ts-jison) seems to be working for this. See it in action in [ShapePath.js](https://github.com/shexSpec/ShapePath.js/blob/main/src/ShapePathParser.jison#L5-L72). That `%{...%}` block imports from an [AST](https://github.com/shexSpec/ShapePath.js/blob/main/src/ShapePathAst.ts) and defines a bunch of parser-only types and functions. I had to place the parser-internal types in [ShapePathParserInternals.ts](https://github.com/shexSpec/ShapePath.js/blob/main/src/ShapePathParserInternals.ts) because test-compiling the [typecheck output](https://github.com/shexSpec/ShapePath.js/blob/main/src/ShapePathParser.typecheck.ts) wasn't finding them even though they were in the same file.

It was a pretty big investment to create the typedict but it paid for itself many times over in catching type errors that would have had to bubble up through human-curated tests.

**Comment by kylejlin** [comment]
Nice!

Previously, as a workaround, I typically instructed the TS compiler to _not_ typecheck JS files, and then created a `parser.d.ts` so I could `import parser from "./parser";`. But with ts-jison, this hack will no longer be necessary. Thanks!

Can I close this issue now, or is there something else that hasn't been addressed?
